### ISSUE TITLE
bfffo instruction used for 030+ ?

### ISSUE THREAD

**Issue by MedourMehdi** [freemint/fdlibm#10]
Hi,

As I understand but I could be wrong bfffo is supported for 020+ cpu.
So [here](https://github.com/freemint/fdlibm/blob/37fa5440ad6fc8affefedbfa766e41e00d5317ea/include/fdlibm.h#L540) I don't understand why this doesn't look like
````
#if defined(__GNUC__) && (defined (__mc68020__) || defined (__mc68030__) || defined (__mc68040__) || defined (__mc68060__) ) && !defined (__mcpu32__)
`````

**Comment by th-otto** [comment]
That's because if you compile for m68020-60, gcc will define *all* the __mc680xx__ symbols for 68020 and above.

But yes, your expression would be clearer.

I think atleast for newer gcc, that ifdef is not even needed, since __builtin_clz should do the same.

**Comment by MedourMehdi** [comment]
Very clear, many thanks.
