### ISSUE TITLE
Math.pow is wrong with negative exponents in chromium

### ISSUE THREAD

**Issue by ValZapod** [freemint/fdlibm#3]
In Android this is a default implementation (as std::pow uses fdlibm under hood) and on windows chromium used std::pow WinAPI implementation; also ECMAScript explicitly recommends using fdlibm. It was unified in this commit (three relands motivated by this https://crbug.com/v8/5848): https://github.com/v8/v8/search?q=%22%5Bbuiltins%5D+%5Bturbofan%5D+Refactor+Float64Pow&type=Commits to use fdlibm everywhere. This caused a decrease in both speed and precision in windows, Mac and Linux (and it was on Android) and sometimes it was outright wrong. For example with https://crbug.com?id=957901 (very nice comments, in some cases the precision is just one bit difference)
1. Open developer tools (F12).
2. Type Math.pow(10, -5) actually prints 9.999999999999999E-6 while the consensus is to print 0.00001 (I know it is not THAT simple (no exact double representation, etc), but it gets worse).

There is also toFixed that returns a string not a JS number thus producing underlying format. With it you can see that the bit pattern of the double value we generated before was 3ee4f8b588e368f1, now it is 3ee4f8b588e368f0 (the LSB changed).
--> exponent 0x3ee, fraction 3ee4f8b588e368f1/ 0x4f8b588e368f0
According to wolfram alpha, the old value had an error of ~8.18e-22, the new value has an error of ~8.76e-22 (note that this is an exact computation):
https://www.wolframalpha.com/input/?i=(1+%2B+(0x4F8B588E368F1+*+2%5E-52))+*+2%5E(0x3ee-1023)+-+10%5E-5
https://www.wolframalpha.com/input/?i=(1+%2B+(0x4F8B588E368F0+*+2%5E-52))+*+2%5E(0x3ee-1023)+-+10%5E-5
Thus the new value (before printing) is less precise than the old value (also see http://weitz.de/ieee/).

Also in binary (looks like something really simple, IMHO)
0b0.0000000000000000101001111100010110101100010001110001101101000111100001000010001100001111110011111...    // true value
0b0.000000000000000010100111110001011010110001000111000110110100011110001                                                     // old value
0b0.00000000000000001010011111000101101011000100011100011011010001111                                                            // new value

"No matter the range of the base and exponent values, when the exponent is a float the old implementation is either as good as or, more commonly, significantly better then the new - although the difference is much less than the improvement of the new implementation when the exponent is an integer."
"Notice though that within the exponent range -24 to 32, i.e. including JS numbers between the ranges -1e+32 to 1e+32, the old implementation is more accurate in the sense that there are 7 exponent values for which it gives the more accurate result, and no exponent values where the new implementation is more accurate." Etc, please read full issue (there is even a zip file with different results across the range).

It caused some problems and other bugs, this https://bugs.chromium.org/p/v8/issues/detail?id=9622 and etc. Thanks, maybe https://github.com/freemint/fdlibm/commit/4e69500bea4af0ff89f30967ca2edb8a9b7fa089 fixes that, @th-otto ?

**Comment by th-otto** [comment]
The commit you reference only implements float/long double versions, the normal (double) version was already there, and is similar (if not identical) to what is used in glibc (although there a softfloat version is maybe rarely used on current hardware).

I'm not familiar with the issues you mention, but generally i think an application should not rely on an implementation to produce a certain bit pattern, that always may change when using different hardware. Its also almost impossible to always produce the same bit pattern in a softfloat version that you get from an FPU; in the case of m68k, there are even differences between models.

**Comment by ValZapod** [comment]
> produce a certain bit pattern,

No, it is across all range. It looks you just drop 4 bites.
 

> (if not identical) to what is used in glibc
Not identical. And not identical to Microsoft C/C++ library.

> that always may change when using different hardware

What???? OMG, we are using this library so IT WILL NOT CHANGE across different hardware😢😢

Can you please at least cinfirm this issue? Or maybe it is our implementation in v8 that is broken see https://github.com/v8/v8/blob/4b9b23521e6fd42373ebbcb20ebe03bf445494f9/src/base/ieee754.cc#L2662

**Comment by th-otto** [comment]
> not identical to Microsoft C/C++ library and MacOS library

So what? What do i care about what MS implements?

>Can you please at least confirm this issue?

Maybe you got something wrong here. This implementation is used for Atari/TOS, and certainly not used in chromium.

**Comment by ValZapod** [comment]
But you can use it on x86_64? No?

BTW, why I am asking. 

> I'm really not sure what's going on here. Over the last few hours I've tried pulling variants of e_pow out of XS and spidermonkey, but inside of V8 they always return the wrong value. e_pow has three external dependencies, s_fabs, s_scalbn, and e_sqrt. My current assumption is that one of these is not behaving properly, but I have yet to test this.

**Comment by th-otto** [comment]
> But you can use it on x86_64? No?

No, not really. It is designed to be used for MiNT/TOS on 68k only. The remaining ifdefs for x86 are only meant for testing purposes, because it is cross-compiled on x86 most of the time.
