### ISSUE TITLE
Questions about IEEE 754 functions.

### ISSUE THREAD

**Issue by PowerUser1234** [freemint/fdlibm#7]
Do the IEEE 754 fdlibm versions of the functions sin, cos, tan, asin, acos, atan, exp, log, log10, cbrt, atan2, pow, sinh, cosh, tanh, hypot, expm1, and log1p also have non-IEEE 754 versions of those functions, that don't allow for the same floating point errors in the values returned, when used in Java SE or OpenJDK, which are unlike the IEEE 754 versions of these functions? Could someone please confirm and reply?

**Comment by mikrosk** [comment]
I'm sorry but I don't understand what are you asking about. Also, do you realize this is an old, m68k-centric, math library?

**Comment by PowerUser1234** [comment]
The functions: sin, cos, tan, asin, acos, atan, exp, log, log10, cbrt, atan2, pow, sinh, cosh, tanh, hypot, expm1, and log1p all come in IEEE 754 versions.  Does the same fdlibm library also contain non-IEEE 754 versions, that are more digit place accurate than the IEEE 754 ones manage not to be from within Java OpenJDK?

**Comment by th-otto** [comment]
I also quite don't understand the question. There is a compile-time option to compile it with SVID semantics, but that mostly has an influence about error handling and NANs, if that is what you are looking for,
