### ISSUE TITLE
Cherry pick 5.3 bugfixes

### ISSUE THREAD

**Issue by MedourMehdi** [freemint/fdlibm#9]
Hi,

The lib used here seems to be v5.2

However [v5.3](https://netlib.org/fdlibm/readme) added some bugfixes.

**Comment by mikrosk** [comment]
> The lib used here seems to be v5.2

Does it? https://github.com/freemint/fdlibm/blob/master/readme

**Comment by MedourMehdi** [comment]
Ah! Yes, it seems. https://github.com/freemint/fdlibm/blob/master/Product-Info says 5.2, so that misled me and thought we were using 5.2

**Comment by mikrosk** [comment]
Feel free to provide a PR if you would like to see the file updated. ;)
